#  ╭──────────────────────────────────────────────────────────╮
#  │                    Networks settings                     │
#  ╰──────────────────────────────────────────────────────────╯
networks:
  back-tier:
    driver: bridge
    name: back_end
  front-tier:
    driver: bridge
    name: front_end


services:

#  ╭──────────────────────────────────────────────────────────╮
#  │                 Proxy container settings                 │
#  ╰──────────────────────────────────────────────────────────╯
  # proxy:
  #   container_name: reverse_proxy
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   ports:
  #   # These ports are in format <host-port>:<container-port>
  #     - '${PROXY_PORT}:${PROXY_PORT}' # Public HTTP Port
  #     - '${HTTPS_PORT}:${HTTPS_PORT}' # Public HTTPS Port
  #     - '${ADM_PORT}:${ADM_PORT}' # Admin web Port
  #   volumes:
  #     - ../proxy/data/:/data
  #     - ../proxy/letsencrypt/:/etc/letsencrypt
  #     - ../proxy/:/etc/nginx
  #   links:
  #     - "db:database"
  #   depends_on:
  #     - "auth_server"
  #     - "web_app"
  #     - "db"
  #   env_file: .env
  #   environment:
  #     NODE_ENV: development
  #     DB_USER: ${PG_USER}
  #     DB_PORT: ${DB_PORT}
  #     DB_HOST: ${PG_HOST}
  #     DB_PASSWORD: ${PG_PASS}
  #     DB_NAME: ${PG_DB}
  #   restart: unless-stopped


#  ╭──────────────────────────────────────────────────────────╮
#  │    Authorization and authentication container server     │
#  ╰──────────────────────────────────────────────────────────╯
  auth_server:
    command: yarn start
    # container_name: auth_server
    depends_on:
      - web_app
      - db
    deploy:
      mode: replicated
      replicas: 2

    env_file: .env
    environment:
      DB_HOST: ${PG_HOST}
      DB_NAME: ${PG_DB}
      DB_PASSWORD: ${PG_PASS}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      NODE_ENV: development
    expose:
      - ${PORT}
    image: node:20.8-alpine3.17
    networks:
      # - front-tier
      - back-tier
    # ports:
    #   - "${PORT}:${PORT}"
    restart: on-failure
    volumes:
      - ../:/usr/api
    working_dir: /usr/api


#  ╭──────────────────────────────────────────────────────────╮
#  │               Database Postgres container                │
#  ╰──────────────────────────────────────────────────────────╯
  db:
    container_name: postgres_container
    env_file: .env
    environment:
      PGHOST: ${PG_HOST}
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
    expose:
      - "5432"
    image: postgres:16-alpine3.18
    networks:
      - back-tier
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: on-failure
    volumes:
      - ../database/DB/data/:/var/lib/postgresql/data


#  ╭──────────────────────────────────────────────────────────╮
#  │                 Proxy container settings                 │
#  ╰──────────────────────────────────────────────────────────╯
  reverse_proxy:
    build: 
      context: ./
    container_name: nginx_proxy
    depends_on:
      - auth_server
      - web_app
      - db
    env_file: .env
    networks:
      - front-tier
      - back-tier
    ports:
    # These ports are in format <host-port>:<container-port>
      - '${PROXY_PORT}:${PROXY_PORT}' # Public HTTP Port
      - '${HTTPS_PORT}:${HTTPS_PORT}' # Public HTTPS Port
      - '${ADM_PORT}:${ADM_PORT}' # Admin web Port
      # - '${PORT1}:${PORT1}' # Public HTTP Port
    restart: always
    volumes:
      - ../proxy/nginx:/var/log/nginx
      - ../otto/:/home/crater


# ╭──────────────────────────────────────────────────────────╮
# │               Main app container settings                │
# ╰──────────────────────────────────────────────────────────╯
  web_app:
    command: yarn start
    container_name: web_app
    depends_on:
      - db

    env_file: .env
    expose:
      - ${PORT1}
    image: node:20.8-alpine3.17
    networks:
      - front-tier
  
    restart: on-failure
    volumes:
      - ../otto/:/crater/app
    working_dir: /crater/app
    # TODO: try out another work directory to pass the '/', as a root path.

version: "3.9"
