// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

export interface CloudflareBindings {
	OTTO_USERS: KVNamespace;
	SECRET_TOKEN: "917910d08e47f27c33c7c53c746aa9f9fa11193cce2110ee619f928ee5c5491ef647f97c87a660cb3249a76525c362ff696c8333dff5648867702299e827fa23";
	REF_SECRET_TOKEN: "101255a9f4429cf2c7adcb70316acd05d12c8ff89310c3c3d32366e559804344b8ca1346de0830adc1abcaab78fc06f83cee88801a286219956577869fbd8207";
	API_KEY: "eyJhbGciOiJIUzI1NiJ9.U2FsdmFkb3I.b8j5EJcaxHRamaaIWfkFQ99GbNQg-HeqZsebtX44n6Y";
	API_KEY2: "736523325468a9d45ba4bd21d24b5475";
	DB: D1Database;
	APP: Fetcher;
	ASSETS: Fetcher;
}
