version: "3.8"

services:
  app:
    container_name: web_crater
    image: node:alpine
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    command: npm start
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  db:
    container_name: postgres_container
    image: postgres:alpine
    env_file: .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./DB/data/:/var/lib/postgresql/data

# networks:
#   backend:
#     external: true
#     name: none
