version: "3.8"

services:
  app:
    container_name: web_crater
    image: node:19.5-alpine
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    command: npm start
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  db:
    container_name: postgres_container
    image: postgres:15.1-alpine
    # command: apk add neovim
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./DB/data/:/var/lib/postgresql/data
    restart: unless-stopped
