// Generated by Wrangler by running `wrangler types`

interface Env {
	ASSETS: Fetcher;
}

export default {
	async fetch(request, env, ctx): Promise<Response> {
		console.log(request)
		const url = new URL(request.url);
		const res = ctx.waitUntil(await fetch(request));

		if (url.pathname.startsWith('/')) {
			return new Response('Ok');
		}
		// Passes the incoming request through to the assets binding.
		// No asset matched this request, so this will evaluate `not_found_handling` behavior.
		//return env.ASSETS.fetch(request);
		return (new Response("Not found!", { status: 404 }));
	},
} satisfies ExportedHandler<Env>;
